import {
  Laptop, Wrench, Recycle, TabletSmartphone, Cable, Plug, Smartphone,
  BatteryFull, Shield, BatteryCharging, Mouse, Package, Usb, ShieldCheck,
  Sparkles, KeyRound, Car, CarFront, Zap, Layers, Speaker, BatteryMedium,
  PlugZap, ShoppingCart, Headphones, Monitor, Watch, Camera, Gamepad2, Tv,
  // — set extins —
  Tv2, Tablet, Keyboard, Printer, HardDrive, Cpu, MemoryStick, CircuitBoard,
  Server, Router, Wifi, Bluetooth, Webcam, Mic, Music, Radio, Disc, Joystick,
  Projector, Cast, MonitorSmartphone, Phone, Battery, Lightbulb, Lamp, Fan,
  Refrigerator, Microwave, WashingMachine, AirVent, CookingPot, Utensils,
  Coffee, Wine, Shirt, Glasses, Footprints, ShoppingBag, Store, Gift, Tag,
  Tags, Heart, Star, Home, Baby, Dog, Cat, Bike, Truck, Bus, Plane, Hammer,
  Drill, PaintRoller, Scissors, Dumbbell, Flower, Leaf, TreePine, Sun,
  Snowflake, Thermometer, Pill, Stethoscope, GraduationCap, BookOpen, Book,
  Briefcase, PenTool, Palette, Clapperboard, Film, Lock,
  type LucideIcon,
} from 'lucide-react'

// Iconitele disponibile pentru categorii. Cheia (kebab-case) se salveaza in
// categories.icon si se alege din pickerul vizual din /admin/categorii.
const ICONS: Record<string, LucideIcon> = {
  // electronice & IT
  'laptop': Laptop,
  'monitor': Monitor,
  'monitor-telefon': MonitorSmartphone,
  'smartphone': Smartphone,
  'telefon': Phone,
  'tableta': Tablet,
  'tableta-touchscreen': TabletSmartphone,
  'tv': Tv,
  'tv-2': Tv2,
  'proiector': Projector,
  'cast': Cast,
  'tastatura': Keyboard,
  'mouse-periferice': Mouse,
  'imprimanta': Printer,
  'hdd': HardDrive,
  'cpu': Cpu,
  'memorie': MemoryStick,
  'placa': CircuitBoard,
  'server': Server,
  'router': Router,
  'wifi': Wifi,
  'bluetooth': Bluetooth,
  'webcam': Webcam,
  'microfon': Mic,
  'camera': Camera,
  'casti': Headphones,
  'boxa': Speaker,
  'muzica': Music,
  'radio': Radio,
  'disc': Disc,
  'gaming': Gamepad2,
  'joystick': Joystick,
  'smartwatch': Watch,
  // conectica & alimentare
  'cablu': Cable,
  'usb': Usb,
  'incarcator': Plug,
  'incarcator-rapid': PlugZap,
  'powerbank': Zap,
  'baterie': BatteryMedium,
  'baterie-plina': BatteryFull,
  'baterie-medie': Battery,
  'baterie-incarcare': BatteryCharging,
  // electrocasnice & casa
  'frigider': Refrigerator,
  'cuptor-microunde': Microwave,
  'masina-spalat': WashingMachine,
  'aer-conditionat': AirVent,
  'ventilator': Fan,
  'oala': CookingPot,
  'tacamuri': Utensils,
  'cafea': Coffee,
  'vin': Wine,
  'bec': Lightbulb,
  'veioza': Lamp,
  'casa': Home,
  'termometru': Thermometer,
  // moda & lifestyle
  'haine': Shirt,
  'ochelari': Glasses,
  'incaltaminte': Footprints,
  'geanta': ShoppingBag,
  'magazin': Store,
  'cadou': Gift,
  'eticheta': Tag,
  'etichete': Tags,
  'cos': ShoppingCart,
  'inima': Heart,
  'stea': Star,
  // auto & mobilitate
  'auto': Car,
  'suport-auto': CarFront,
  'bicicleta': Bike,
  'camion': Truck,
  'autobuz': Bus,
  'avion': Plane,
  // unelte & bricolaj
  'cheie': Wrench,
  'ciocan': Hammer,
  'bormasina': Drill,
  'trafalet': PaintRoller,
  'foarfeca': Scissors,
  // copii, animale, gradina
  'bebe': Baby,
  'caine': Dog,
  'pisica': Cat,
  'floare': Flower,
  'frunza': Leaf,
  'brad': TreePine,
  'soare': Sun,
  'fulg': Snowflake,
  // sanatate, sport, birou, hobby
  'sport': Dumbbell,
  'medicament': Pill,
  'stetoscop': Stethoscope,
  'educatie': GraduationCap,
  'carte': Book,
  'carte-deschisa': BookOpen,
  'birou': Briefcase,
  'creion': PenTool,
  'paleta': Palette,
  'film': Film,
  'cinema': Clapperboard,
  // diverse
  'accesorii': Package,
  'recond': Wrench,
  'second-hand': Recycle,
  'nou': Sparkles,
  'husa': Layers,
  'licenta': KeyRound,
  'lacat': Lock,
  'folie-protectie': Shield,
  'folie-verificata': ShieldCheck,
}

export const CATEGORY_ICON_NAMES = Object.keys(ICONS)

export function CategoryIcon({ name, className }: { name?: string | null; className?: string }) {
  const Icon = (name && ICONS[name]) || ShoppingCart
  return <Icon className={className} aria-hidden="true" />
}
